name: "Publish artifacts"

on:
  release:
    types: [ created ]

permissions: read-all

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Build and publish with Maven
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
          SONATYPE_TOKEN_USERNAME: ${{ secrets.SONATYPE_TOKEN_USERNAME }}
          SONATYPE_TOKEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
        run: ./mvnw --batch-mode -s .mvn/ci_settings.xml -ntp -DskipTests -Prelease
